title: pdfVise
description: >- # this means to ignore newlines until "baseurl:"
  Generic PDF operations through JavaScript.
logo: "/assets/images/logo.jpg"
theme_color: "#db2f47"

safe: true
# verbose: true
permalink: none
# destination: docs

# Build settings
sass:
  style: compressed

plugins:
  - jekyll-sitemap

include:
 - _pages
 - .htaccess

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - desktop.ini

defaults:
  -
    scope:
      path: ""
    values:
      layout: "empty"
      lang: "en"
  -
    scope:
      path: "_pages"
    values:
      sitemap: false